server:
  port: 8083

spring:
  application:
    name: batch-service
  cloud:
    consul:
      host: localhost
      port: 8500
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:sqlserver://l4g.database.windows.net:1433;database=employee-practice
    username: l4gadmin@l4g
    password: "#DDjjL4G"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: validate